FROM apache/airflow:2.10.5-python3.11

USER airflow

COPY requirements.txt /tmp/project-requirements.txt

RUN pip install --no-cache-dir \
    -r /tmp/project-requirements.txt \
    apache-airflow-providers-postgres \
    psycopg2-binary
