from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class TableSpec:
    file_name: str
    primary_key: str | None
    columns: tuple[str, ...]


TABLES: dict[str, TableSpec] = {
    "appearances": TableSpec(
        "appearances.csv",
        "appearance_id",
        (
            "appearance_id",
            "game_id",
            "player_id",
            "player_club_id",
            "player_current_club_id",
            "date",
            "player_name",
            "competition_id",
            "yellow_cards",
            "red_cards",
            "goals",
            "assists",
            "minutes_played",
        ),
    ),
    "club_games": TableSpec(
        "club_games.csv",
        None,
        (
            "game_id",
            "club_id",
            "own_goals",
            "own_position",
            "own_manager_name",
            "opponent_id",
            "opponent_goals",
            "opponent_position",
            "opponent_manager_name",
            "hosting",
            "is_win",
        ),
    ),
    "clubs": TableSpec(
        "clubs.csv",
        "club_id",
        (
            "club_id",
            "club_code",
            "name",
            "domestic_competition_id",
            "total_market_value",
            "squad_size",
            "average_age",
            "foreigners_number",
            "foreigners_percentage",
            "national_team_players",
            "stadium_name",
            "stadium_seats",
            "net_transfer_record",
            "coach_name",
            "last_season",
            "filename",
            "url",
        ),
    ),
    "competitions": TableSpec(
        "competitions.csv",
        "competition_id",
        (
            "competition_id",
            "competition_code",
            "name",
            "sub_type",
            "type",
            "country_id",
            "country_name",
            "domestic_league_code",
            "confederation",
            "total_clubs",
            "url",
        ),
    ),
    "countries": TableSpec(
        "countries.csv",
        "country_id",
        (
            "country_id",
            "country_name",
            "country_code",
            "confederation",
            "total_clubs",
            "total_players",
            "average_age",
            "url",
        ),
    ),
    "game_events": TableSpec(
        "game_events.csv",
        "game_event_id",
        (
            "game_event_id",
            "date",
            "game_id",
            "minute",
            "type",
            "club_id",
            "club_name",
            "player_id",
            "description",
            "player_in_id",
            "player_assist_id",
        ),
    ),
    "game_lineups": TableSpec(
        "game_lineups.csv",
        "game_lineups_id",
        (
            "game_lineups_id",
            "date",
            "game_id",
            "player_id",
            "club_id",
            "player_name",
            "type",
            "position",
            "number",
            "team_captain",
        ),
    ),
    "games": TableSpec(
        "games.csv",
        "game_id",
        (
            "game_id",
            "competition_id",
            "season",
            "round",
            "date",
            "home_club_id",
            "away_club_id",
            "home_club_goals",
            "away_club_goals",
            "home_club_position",
            "away_club_position",
            "home_club_manager_name",
            "away_club_manager_name",
            "stadium",
            "attendance",
            "referee",
            "url",
            "home_club_formation",
            "away_club_formation",
            "home_club_name",
            "away_club_name",
            "aggregate",
            "competition_type",
        ),
    ),
    "national_teams": TableSpec(
        "national_teams.csv",
        "national_team_id",
        (
            "national_team_id",
            "name",
            "team_code",
            "country_id",
            "country_name",
            "country_code",
            "confederation",
            "team_image_url",
            "squad_size",
            "average_age",
            "foreigners_number",
            "foreigners_percentage",
            "total_market_value",
            "coach_name",
            "fifa_ranking",
            "last_season",
            "url",
        ),
    ),
    "player_valuations": TableSpec(
        "player_valuations.csv",
        None,
        (
            "player_id",
            "date",
            "market_value_in_eur",
            "current_club_name",
            "current_club_id",
            "player_club_domestic_competition_id",
        ),
    ),
    "players": TableSpec(
        "players.csv",
        "player_id",
        (
            "player_id",
            "first_name",
            "last_name",
            "name",
            "last_season",
            "current_club_id",
            "player_code",
            "country_of_birth",
            "city_of_birth",
            "country_of_citizenship",
            "date_of_birth",
            "sub_position",
            "position",
            "foot",
            "height_in_cm",
            "contract_expiration_date",
            "agent_name",
            "image_url",
            "international_caps",
            "international_goals",
            "current_national_team_id",
            "url",
            "current_club_domestic_competition_id",
            "current_club_name",
            "market_value_in_eur",
            "highest_market_value_in_eur",
        ),
    ),
    "transfers": TableSpec(
        "transfers.csv",
        None,
        (
            "player_id",
            "transfer_date",
            "transfer_season",
            "from_club_id",
            "to_club_id",
            "from_club_name",
            "to_club_name",
            "transfer_fee",
            "market_value_in_eur",
            "player_name",
        ),
    ),
}


RELATIONSHIPS = (
    "games.home_club_id -> clubs.club_id",
    "games.away_club_id -> clubs.club_id",
    "club_games.game_id -> games.game_id",
    "club_games.club_id -> clubs.club_id",
    "appearances.game_id -> games.game_id",
    "appearances.player_id -> players.player_id",
    "game_events.game_id -> games.game_id",
    "game_events.club_id -> clubs.club_id",
    "game_events.player_id -> players.player_id",
    "game_lineups.game_id -> games.game_id",
    "game_lineups.player_id -> players.player_id",
    "player_valuations.player_id -> players.player_id",
    "transfers.player_id -> players.player_id",
)

